In [4]:
import numpy as np

# Define global variables
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def array_operations():
    global arr_1d, arr_2d
    
    # Print arrays
    print("1D Array:", arr_1d)
    print("2D Array:\n", arr_2d)
    
    # Perform basic operations
    print("Sum of 1D Array:", np.sum(arr_1d))
    print("Mean of 2D Array:", np.mean(arr_2d))
    print("Transpose of 2D Array:\n", arr_2d.T)

# Call the function\array_operations()
array_operations()

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of 1D Array: 15
Mean of 2D Array: 5.0
Transpose of 2D Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [5]:
import numpy as np

def image_processing():
    # Creating a grayscale image using a 2D NumPy array
    image = np.random.randint(0, 256, (5, 5), dtype=np.uint8)
    print("Original Image:\n", image)
    
    # Slicing a portion of the image
    cropped = image[1:4, 1:4]
    print("Cropped Section:\n", cropped)
    
    # Inverting colors
    inverted_image = 255 - image
    print("Inverted Image:\n", inverted_image)

# Call the function
image_processing()


Original Image:
 [[ 31 155  92  32 244]
 [ 58  27 240  41  77]
 [209  49 245  26 224]
 [ 26  34 145  67  74]
 [ 19  24  43 125 249]]
Cropped Section:
 [[ 27 240  41]
 [ 49 245  26]
 [ 34 145  67]]
Inverted Image:
 [[224 100 163 223  11]
 [197 228  15 214 178]
 [ 46 206  10 229  31]
 [229 221 110 188 181]
 [236 231 212 130   6]]


In [ ]:
import numpy as np
import cv2

# Load an image
image = cv2.imread('image.jpg')  # Use your own image

# Scaling Transformation
def scale_image(image, scale_factor):
    # Create the scaling matrix
    scaling_matrix = np.array([[scale_factor, 0, 0],
                               [0, scale_factor, 0],
                               [0, 0, 1]], dtype=np.float32)  # Ensure float32 type
    
    # Get the image dimensions
    rows, cols = image.shape[:2]
    
    # Apply the transformation
    scaled_image = cv2.warpPerspective(image, scaling_matrix, (cols, rows))
    return scaled_image

# Rotation Transformation
def rotate_image(image, angle):
    # Get the image dimensions
    rows, cols = image.shape[:2]
    
    # Get the rotation matrix
    rotation_matrix = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 1)
    
    # Apply the rotation
    rotated_image = cv2.warpAffine(image, rotation_matrix, (cols, rows))
    return rotated_image

# Translation Transformation
def translate_image(image, tx, ty):
    # Create the translation matrix
    translation_matrix = np.array([[1, 0, tx],
                                   [0, 1, ty],
                                   [0, 0, 1]], dtype=np.float32)  # Ensure float32 type
    
    # Get the image dimensions
    rows, cols = image.shape[:2]
    
    # Apply the transformation
    translated_image = cv2.warpPerspective(image, translation_matrix, (cols, rows))
    return translated_image

# Example transformations
scaled_image = scale_image(image, 1.5)  # Scale by a factor of 1.5
rotated_image = rotate_image(image, 45)  # Rotate by 45 degrees
translated_image = translate_image(image, 50, 30)  # Translate by 50 pixels along x and 30 pixels along y

# Show the results
cv2.imshow('Original', image)
cv2.imshow('Scaled', scaled_image)
cv2.imshow('Rotated', rotated_image)
cv2.imshow('Translated', translated_image)

# Save the transformed images (optional)
cv2.imwrite('scaled_image.jpg', scaled_image)
cv2.imwrite('rotated_image.jpg', rotated_image)
cv2.imwrite('translated_image.jpg', translated_image)

# Wait for a key press and close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
import cv2 
import numpy as np 
 
# Load an image and convert it to a NumPy array 
image = cv2.imread('image.png')  
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
 
# Load OpenCV's pre-trained Haar Cascade for face detection 
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 
'haarcascade_frontalface_default.xml') 
 
# Detect faces in the image 
faces = face_cascade.detectMultiScale(image_gray, scaleFactor=1.1, 
minNeighbors=5) 
 
# Loop through the detected faces and extract facial features (regions) 
for (x, y, w, h) in faces: 
    # Slice the image array to extract the face region 
    face_region = image[y:y+h, x:x+w] 
     
    # Optional: Display the face region 
    cv2.imshow('Face Region', face_region) 
    cv2.imwrite('face_region.jpg', face_region)
     
    # Extract additional facial features if required (e.g., eyes, nose) 
    eyes_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 
'haarcascade_eye.xml') 
    eyes = eyes_cascade.detectMultiScale(face_region, scaleFactor=1.1, 
minNeighbors=5) 
     
    for (ex, ey, ew, eh) in eyes: 
        eye_region = face_region[ey:ey+eh, ex:ex+ew] 
        cv2.imshow('Eye Region', eye_region) 
        cv2.imwrite('eye_region.jpg', eye_region)
 
# Show the original image with detected faces 
cv2.imshow('Detected Faces', image) 
cv2.imwrite('detected_faces.jpg', image)


 
cv2.waitKey(0) 
cv2.destroyAllWindows()